# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc "Multi-repo workspace manager using git worktrees"
  homepage "https://github.com/milldr/flow"
  version "1.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  on_macos do
    url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
    sha256 "d205a242e37bf89f447f01612045eedfe1dd54ece1f0980a6ebfe30ebb8aa9ac"
  end

  on_linux do
    on_intel do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
      sha256 "bbe19f9b6efc0eb74af75005d68e8790a7d3bc88b08fc96e3dd55cf9d6cd32f4"
    end
    on_arm do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
      sha256 "2cf56a54c3e36b122ccc3177773b60ee2cf3c0c1c3b7fe1c36f824768faf921b"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
