# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc "Multi-repo workspace manager using git worktrees"
  homepage "https://github.com/milldr/flow"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  on_macos do
    url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
    sha256 "4cb3b9ea6c851743245081e48c05fec5854e5563d68363806f17718065659bb7"
  end

  on_linux do
    on_intel do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
      sha256 "79c95d12162e153080f2da646e84f441140a5cbc9d691e24d21853ca5f19d1cc"
    end
    on_arm do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
      sha256 "92f78259aa4d21dd31cfe5ea5e47459436d754b56af7c1792e823429c5513f6c"
    end
  end

  # No zap stanza required
end
