# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc "Multi-repo workspace manager using git worktrees"
  homepage "https://github.com/milldr/flow"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  on_macos do
    url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_darwin_all.tar.gz"
    sha256 "65ba35c47e3f3289a424917dc29d5fcc23a42d4963823696856e20344d49a230"
  end

  on_linux do
    on_intel do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
      sha256 "ee9e8fa151a70b965ca30581fbd7a9bbffa9180e8f3227997cfc986433d338a6"
    end
    on_arm do
      url "https://github.com/milldr/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
      sha256 "94effd9cf8c3e5d63fe5bbeb54d4081fced1bb5f3660d89e6ec5acbd9d818aac"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
